--------------------------------------------------------
--  File created - Wednesday-May-21-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table METHOD
--------------------------------------------------------

  CREATE TABLE "NLFWA"."METHOD" 
   (	"STATE" CHAR(2 BYTE), 
	"METHOD" VARCHAR2(50 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(15 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"PHONE_NUMB" VARCHAR2(100 BYTE), 
	"AGENCY" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(35 BYTE), 
	"ZIP" VARCHAR2(15 BYTE), 
	"FAX" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"STATEURL" VARCHAR2(250 BYTE), 
	"STATEURLTEXT" VARCHAR2(100 BYTE), 
	"CURRINFO" CHAR(1 BYTE), 
	"AFFILIATION" VARCHAR2(20 BYTE), 
	"IS_DEFAULT" CHAR(1 BYTE) DEFAULT 'N'
   ) ;

   COMMENT ON COLUMN "NLFWA"."METHOD"."STATE" IS 'State';
   COMMENT ON COLUMN "NLFWA"."METHOD"."METHOD" IS 'Method Followed by states issuing advisories';
   COMMENT ON COLUMN "NLFWA"."METHOD"."LNAME" IS 'Last name';
   COMMENT ON COLUMN "NLFWA"."METHOD"."FNAME" IS 'First name';
   COMMENT ON COLUMN "NLFWA"."METHOD"."NAME" IS 'Full Name';
   COMMENT ON COLUMN "NLFWA"."METHOD"."TITLE" IS 'Title';
   COMMENT ON COLUMN "NLFWA"."METHOD"."PHONE_NUMB" IS 'Phone Number';
   COMMENT ON COLUMN "NLFWA"."METHOD"."AGENCY" IS 'Agency Name';
   COMMENT ON COLUMN "NLFWA"."METHOD"."ADDRESS" IS 'Street address';
   COMMENT ON COLUMN "NLFWA"."METHOD"."CITY" IS 'City';
   COMMENT ON COLUMN "NLFWA"."METHOD"."ZIP" IS 'Zip';
   COMMENT ON COLUMN "NLFWA"."METHOD"."FAX" IS 'Fax number';
   COMMENT ON COLUMN "NLFWA"."METHOD"."EMAIL" IS 'E mail address';
   COMMENT ON COLUMN "NLFWA"."METHOD"."STATEURL" IS 'URL of organizations fish consumption advisory web site';
   COMMENT ON COLUMN "NLFWA"."METHOD"."STATEURLTEXT" IS 'Text description of orgs fish consumption advisory web site';
   COMMENT ON COLUMN "NLFWA"."METHOD"."CURRINFO" IS 'Weather Contact information is known to be current';
   COMMENT ON COLUMN "NLFWA"."METHOD"."AFFILIATION" IS 'Type of entity this contact is affiliated with';
   COMMENT ON COLUMN "NLFWA"."METHOD"."IS_DEFAULT" IS 'Flag indicating whether this contact is the "primary" contact for the state.  NOTE: Each state must have at most ONE record marked as "Y", otherwise any queries expecting only ONE primary record per state will fail.';
   COMMENT ON TABLE "NLFWA"."METHOD"  IS 'Contact info for the organizations issuing advisories';
  GRANT SELECT ON "NLFWA"."METHOD" TO "RAD_PROGRAMS" WITH GRANT OPTION;
  GRANT SELECT ON "NLFWA"."METHOD" TO "NLFWA_MAP";
  GRANT SELECT ON "NLFWA"."METHOD" TO "NLFWA_WEB";
REM INSERTING into NLFWA.METHOD
SET DEFINE OFF;
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('AB','NA','Berry','Dave','Dave K. Berry','Recreational Fisheries Coordinator','(403) 427-6730','Fisheries Management Division','Main Floor, North Tower Petroleum Plaza, 9945-108th Street','Edmonton','T5K2G6','(403) 422-9559',null,'http://www.albertaregulations.ca/fishingregs/other-information.html','Alberta Outdoorsman - Fish Consumption Advisory','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('AK','Risk Assessment','Coburn','Sarah','Sarah Coburn',null,'(651) 201-4243','Alaska Dept of Environmental Conservation','5251 Dr. Martin Luther King Jr. Ave.','Anchorage, AK','99507','(907) 929-7335','sarah.coburn@alaska.gov','http://dhss.alaska.gov/dph/Epi/eph/Pages/fish/default.aspx','Alaska Fish Facts & Consumption guidelines','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('AL','FDA Limits','Guarisco','John','John A. Guarisco',null,'(334) 206-5971','Alabama DPH, Div.of Epidemiology','Suite 1450,The RSA Tower, 201 Monroe Street','Montgomery, AL','36104','(334) 206-3734','John.Guarisco@adph.state.al.us','http://www.adph.org/tox/index.asp?ID=1360','Alabama Fish Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('AR','FDA Limits','Whitlow','Ashley','Ashley Whitlow',null,'(501) 280-4041','AR Dept. of Health, Environmental Epidemiology','4815 W. Markham St. Slot 32','Little Rock, AR','72205','(501) 661-4090','Ashley.whitlow@arkansas.gov','https://www.healthy.arkansas.gov/programs-services/topics/fish-advisories','Arkansas Environmental Epidemiology','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('AZ','FDA Limits','Goodfellow','Josh','Josh Goodfellow',null,'602-904-2183','AZ Dept. of Environmental Quality','Mailcode 5415A-1, 1110 W Washington St','Phoenix, AZ','85007','(602) 207-4528','goodfellow.josh@azdeq.gov','https://azdeq.gov/fca','Arizona Fish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('BC','NA','Knapp','Wayne','Communications Branch',null,'(604) 666-7120','BC Fisheries and Oceans','401 Burrad St','Vancouver','V6B 5G3','(604) 666-1847','info@dfo-mpo.gc.ca','http://www.health.gov.bc.ca/','Province of British Columbia Homepage  (no fish advisory information found on province web page)','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('CA','Risk Assessment','Smith','Wesley','Wesley Smith',null,'(916) 323-9667','Cal EPA, Office of Environmental Health Hazard Assessment','Mailstop 12B, PO BOX 4010','Sacramento, CA','95812-4010','(916) 327-7320','Wesley.Smith@oehha.ca.gov','http://www.oehha.ca.gov/fish.html','California EPA - Fish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('CO','Risk Assessment','Erickson','Sarah','Sarah Erickson',null,'(303) 692-3505','CO Department of Public Health & Environment','WQCD/UA/B2-4300 Cherry Creek Drive','South Denver, CO','80246','(303) 691-7802','sarah.erickson@state.co.us','https://cdphe.colorado.gov/water-quality/clean-water/rivers-lakes-and-streams/fish-consumption','Colorado Fish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('CT','Both','Rusnak','Sharee','Sharee Rusnak',null,'(860) 509-7583','CT DPH, Environmental and Occupational Health Assessment Program','410 Capitol Ave.','Hartford, CT','06134','(860) 509-7785','Sharee.Rusnak@ct.gov','http://www.ct.gov/dph/cwp/view.asp?a=3140&q=387460&dphNav_GID=1828&dphPNavCtr=|#47464','Connecticut Department of Public Health','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('DE','Risk Assessment','Cargill','John','John G. Cargill, IV',null,'302-395-2600 (New Castle) or 302-739-9939 (Dover)','Delaware DNREC Watershed Assessment & Management Section','100 W. Water St., Suite 10B','Dover, DE','19904','(302) 739-6140','John.Cargill@state.de.us','https://dnrec.alpha.delaware.gov/fish-wildlife/fishing/consumption-advisories/','Fish Advisory Information for Delaware','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('FL','Risk Assessment','Mitchell','Michael','Michael Mitchell',null,'(850) 901-6930','Florida Department of Health','4052 Bald Cypress Way, Bin A08','Tallahassee, FL','32399-1720',null,'Michael.Mitchell@flhealth.gov','http://www.doh.state.fl.us/environment/medicine/fishconsumptionadvisories/index.html','Florida Fish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('GU','NA','Leon-Guerrero','Walter','Walter Leon-Guerrero',null,'(671) 475-1664','Guam Environmental Protection Agency','P.O. Box 22439','GMF Barrigada, GU','96921',null,'Walter.LeonGuerrero@epa.guam.gov','http://www.wpcouncil.org/fisheries/guam-mariana-archipelago/','Guam Environmental Protection Agency','Y','Territory','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('HI','Risk Assessment','Felton','Diana','Diana Felton',null,'(808) 586-0963','Dept. of Health, Hazard Evaluation & Emergency Response','919 Ala Moana Blvd','Honolulu, HI','96814','(808) 586-7357','diana.felton@doh.hawaii.gov','https://health.hawaii.gov/heer/2019/08/26/updated-fish-consumption-brochure/','Hawaii Department of Health -A Local Guide to Eating Fish Safely','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('IA','FDA Limits','Krier','Ken','Ken Krier',null,'(515) 725-8380','Iowa Department of Natural Resources','502 E. 9th St. ','Des Moines, IA','50319-0034','(515) 281-8895','ken.krier@dnr.iowa.gov','http://www.iowadnr.gov/Environmental-Protection/Water-Quality/Water-Monitoring/Fish-Tissue','Iowa DNR - Fish Tissue Monitoring','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('ID','Risk Assessment','Adams','Colby','Colby Adams',null,'(208) 334-4964','ID Dept. of Health and Welfare, Bureau of Community & Environmental Health','P.O. Box 83720, 450 West State St','Boise, ID','83720-0036','(208) 334-6573','colby.adams@dhw.idaho.gov','http://healthandwelfare.idaho.gov/Health/EnvironmentalHealth/FishAdvisories/tabid/180/Default.aspx','Fish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('IL','FDA Limits','Irlam','Justin','Justin Irlam',null,'(217) 524-0073','IL Environmental Protection Agency','1021 North Grand Ave. East P.O. Box 19276','Springfield, IL','62794-9276','(217) 782-1431','justin.irlam@illinois.gov','http://dph.illinois.gov/topics-services/environmental-health-protection/toxicology/fish-advisories','Illinois Fish Advisory','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('IN','Risk Assessment (Great Lakes Protocol)','Meils','Alison','Alison Meils',null,'(317) 308-3204','Targeted Monitoring Section, Watershed Assessment and Planning Branch, Office of Water Quality, Indiana','100 North Senate Avenue
MC65-40-2 Shadeland
','Indianapolis, IN','46204-2251','(317) 308-3219','AMEILS@idem.IN.gov','http://www.in.gov/isdh/23650.htm','Indiana Fish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('KS','Risk Assessment (under review)','Lapin','Jack','Jack Lapin',null,'(785) 291-3676','Kansas Department of Health and Environment','1000 SW Jackson Street','Topeka, KS','66612','(785) 291-3266','Jack.Lapin@ks.gov','https://www.kdhe.ks.gov/civicalerts.aspx?aid=77','Kansas Department of Health and Environment - Fish Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('KY','FDA Limits','Arnold','Melanie','Melanie Arnold',null,'(502) 782-6879','Kentucky Food Saftey Branch','275 E Main Street HS1C-F ','Frankfort, KY','40621',null,'melanie.arnold@ky.gov','http://fw.ky.gov/Fish/Pages/Fish-Consumption-Advisories.aspx','Kentucky Department of Fish and Wildlife - Fish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('LA','Risk Assessment','Soileau','Shannon','Shannon Soileau',null,'(504) 568-8150','Office of Public Health Section of Env. Epidemiology and Toxicology','P.O.Box 60630 ','New Orleans, LA','70160','(504) 568-8149','shannon.soileau@la.gov','http://www.ldh.la.gov/index.cfm/page/564','LA Dept of Health and Hospitals - Fish Consumption Advisories Program','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('MA','Both','Blanchet','Meg','Meg Blanchet',null,'(617) 624-5757','MA DPH Bureau of Climate and Environmental Health','250 Washington St.','Boston, MA','02108','(617) 624-5777','meg.blanchet@mass.gov','https://www.mass.gov/lists/fish-consumption-advisories','Public Health Fish Consumption Advisory','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('MB','NA','Green','Dave','Dave Green',null,'(204) 945-0585','Manitoba Water Stewardship','139 Tuxedo Avenue, Bldg. 2','Winnipeg','R3N OH6','(204) 948-2357','dgreen@gov.mb.ca','http://www.gov.mb.ca/cgi-bin/choose_home.pl','Province of Manitoba Homepage','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('MD','Both','Laliberte','Amy','Amy Laliberte',null,'(410) 537-3614','MD Dept. of Environment','1800 Washington Blvd., Ste. 540 ','Baltimore, MD','21230-1718','(410) 537-3873','Amy.Laliberte@Maryland.gov','https://mde.maryland.gov/programs/Marylander/fishandshellfish/Pages/fishconsumptionadvisory.aspx','Maryland Department of the Environment - Fish Consumption Advisory','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('ME','Both','Simones','Tom','Tom Simones',null,'(207) 287-3365','Maine CDC Environmental and Occupational Health Program','286 Water Street, 3rd Floor, 11 State House Station','Augusta, ME','04333','(207) 287-3981','Thomas.simones@maine.gov','http://www.maine.gov/dhhs/mecdc/environmental-health/eohp/fish/','Warnings on Eating Fish and Game','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('MI','Both','Reid','Brandon','Brandon Reid',null,'(517) 897-3552','MI Dept. of Health and Human Services, Division of Environmental Health','333 South Grand Avenue','Lansing, MI','48913','(517) 335-8800','ReidB1@michigan.gov','http://www.michigan.gov/eatsafefish','Michigan Fish Advisory','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('MN','Risk Assessment','Preimesberger','Angela L.H.','Angela L.H. Preimesberger',null,'(651) 201-4243','MN Department of Health, Div. of Environ. Health','625 Roberts St N, P.O.Box 64975 ','St. Paul, MN','55164-0975','(651) 201-4606','angela.preimesberger@state.mn.us','https://www.health.state.mn.us/communities/environment/fish/','Minnesota Department of Health - Fish Consumption Advisory','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('MO','Risk Assessment','Wenzel','Jeff','Jeff Wenzel',null,'(573) 751-6102','MO Dept. of Health and Senior Services, Section for Environmental Public He','P.O. Box 570-930 Wildwood Dr ','Jefferson City, MO','65102','(573) 526-6946','jeff.wenzel@health.mo.gov','http://health.mo.gov/living/environment/fishadvisory/index.php','Missouri Fish Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('MS','Both','Ulmer','Jennifer','Jennifer Ulmer',null,'(601) 961-5632','MDEQ, Field Services','P.O. Box 2261','Jackson, MS','39225','(601) 961-5704','julmer@mdeq.ms.gov','https://www.mdeq.ms.gov/water/field-services/fish-advisories-fish-tissue-and-fishing-bans/','MDEQ - Mississippi Fish Advisories Field Services Division','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('MT','Risk Assessment','Selch','Trevor','Trevor M. Selch',null,'(406) 444-5686','Montana Fish, Wildlife & Parks','1420 E. 6th Ave, PO Box 200701','Helena, MT','59620-0701','(406) 444-4952 ','TSelch@mt.gov','http://fwp.mt.gov/fish','Montana Fish, Wildlife and Parks - Fishing','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NB','NA','MacLean','Scott','Scott MacLean','Director','(506) 453-2427','NB Dept. of Health','1350 Regent Street, Room 120 Fredericton, NB E3C 2G6','Fredericton','E3C 2G6',null,'scott.maclean@gnb.ca','http://www.gov.nb.ca/','Province of New Brunswick','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NC','Risk Assessment','Holt','Kennedy','Kennedy Holt',null,'(919) 707-5910','North Carolina Department of Health and Human Services','1902 Mail Service Center','Raleigh, NC','27699-1902',null,'Kennedy.Holt@dhhs.nc.gov','http://epi.publichealth.nc.gov/oee/programs/fish.html','North Carolina Fish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('ND','Risk Assessment','Larsen','Aaron','Aaron Larsen',null,'(701) 328-5230','ND Environmental Quality','4201 Normandy Street','Bismarck, ND','58503','(701) 328-5200','allarsen@nd.gov','https://deq.nd.gov/WQ/WQ_FishAdvisory.aspx','North Dakota Department of Health: scroll down to "Fish Consumption Advisories"','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NE','Both','Michl','Greg','Greg Michl',null,'(402) 471-4264','NE Department of Environmental Quality','Suite 400 The Atrium, 1200 N Street, PO Box 98922','Lincoln, NE','68509-8922','(402) 471-2909','greg.michl@nebraska.gov','http://deq.ne.gov/NDEQProg.nsf/OnWeb/FCA','Nebraska Game & Parks Commission Fishing Guide','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NF','NA','Adams','Blair','Dr. Blair Adams',null,'(709) 637-2112','Department of Environment and Conservation; Wildlife Division','PO BOX 2007 Cornerbrook St.  John''s, NF A2H7S1','St. John''s','A1B 4J6','(709) 637-2080','blairadams@gov.nl.ca','http://www.gov.nf.ca/','Province of New Foundland Homepage - (NF has no fish advisories)','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NH','Risk Assessment','Petali','Jonathan','Jonathan Petali',null,'(603) 271-1359','NH Department of Environmental Services','29 Hazen Drive, PO Box 95','Concord, NH','03302','(603) 271-7053','jonathan.m.petali@des.nh.gov','https://www.wildlife.state.nh.us/fishing/consume-fresh.html','Mercury in NH''s Fish Fact Sheet and Consumption Advisory.','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NJ','Both','Millemann','Dan','Dan Millemann',null,'(609) 984-4023','Dept. Env. Protection, Div Science and Research','P.O. Box 409 401 East State St.','Trenton, NJ','08625','(609) 292-7340','Dan.Millemann@dep.nj.gov','https://www.state.nj.us/dep/dsr/njmainfish.htm','New Jersey Department of Environmental Protection','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NM','Risk Assessment','Schiffmiller','Gary','Gary Schiffmiller',null,'(505) 827-2470','NM Surface Water Quality Bureau','1190 St. Francis Dr., P.O. Box 26110','Santa Fe, NM','87502','(505) 827-0160','gary.schiffmiller@state.nm.us','https://www.env.nm.gov/surface-water-quality/fish-consumption-advisories/','New Mexico Fish Consumption Guidelines Due to Mercury Contamination','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NS','NA','Hill','Murray','Murray Hill',null,'(902) 485-7021','Inland Fisheries Division','91 Beeches Road','Pictou','B0K 1H0','(902)485-4014','inland@gov.ns.ca','http://www.gov.ns.ca/','Province of Nova Scotia Homepage','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NT','NA','Self','Lisette','Lisette Self',null,'(403) 920-8064','Dept. of Renewable Resources','P.O. BOX 1320 Yellowknife','Yellowknife','X1A 2L9',null,'lisette_self@gov.nt.ca','http://www.gov.nt.ca/','Northwest Territories Homepage','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NV','Risk Assessment','Heggeness','John','John Heggeness',null,'(775) 687-9449','Nevada Division of Environmental Protection','901 South Stewart, Suite 4001','Carson City, NV','89701','(775) 687-9561','jheggene@ndep.nv.gov','https://www.ndow.org/get-outside/fishing/plan-your-fishing-trip/','Nevada Department of Wildlife - Fishing in Nevada','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('OH','Both; other','Buck-Priddy','Allison','Allison Buck-Priddy',null,'(614) 644-4797','OH Department of Health','246 N. High Street','Columbus, OH','43215','(614) 644-2745','allison.buck-priddy@odh.ohio.gov','https://odh.ohio.gov/know-our-programs/ohio-sport-fish-consumption-advisory','Ohio Department of Health - Ohio Sportfish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('OK','FDA Limits','Jones','Jaymes','Jaymes Jones',null,'(405) 702-1017','OK Department of Environmental Quality','707 N. Robinson','Oklahoma City, OK','73101-1677','(405) 702-1001','Jayme.Jones@deq.ok.gov','https://www.deq.ok.gov/state-environmental-laboratory-services/environmental-public-health-information/healthy-fish-consumption-in-oklahoma/','Oklahoma Dept of Env Quality Website','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('ON','NA','Bhavsar','Satyendra','Satyendra Bhavsar',null,'(416) 327-5863','Sport Fish Contaminant Monitoring Program','125 Resource Road','Etobicoke','M9P 3V6','(416) 327-6519','satyendra.bhavsar@ontario.ca','http://www.ene.gov.on.ca/envision/guide/','Province of Ontario Ministry of the Environment - Guide to Eating Ontario Sportfish','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('OR','Risk Assessment','Farrer','Dave','Dave Farrer',null,'(971) 673-1222','Oregon Health Authority','246 N. High Street','Columbus, OH','43215','(971) 673-0457','david.g.farrer@dhsoha.state.or.us','http://public.health.oregon.gov/HealthyEnvironments/Recreation/FishConsumption/Pages/index.aspx','Oregon Health Division - Fish Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('PE','NA','McDougall','Gerald','Gerald McDougall',null,'(902) 368-5111','Fish and Wildlife Division','183 Uptton Rd.','Charlottetown','C1A 7N8','(902)368-4713','mgmcdougall@gov.epa.pe.ca','http://www.gov.pe.ca/infopei/index.php3?number=44581&lang=E','Prince Edward Island - Fisheries, Aquaculture, and Environment','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('PR','NA','TBD',null,'TBD',null,'(602) 771-8787','Departamento de Salud','Centro Médico Norte, Calle Periferial Interior, Bo. Monacillos','Río Piedras, PR',' ','(787) 751-6937','Currently unavailable','https://www.drna.pr.gov/programa-de-estadisticas-de-pesca-recreativa-marina/','Puerto Rico Health Department','Y','Territory','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('QC','NA','Laliberte','Denis','Denis Laliberte','Aquatic Ecosystem Department','(418) 521-3820','Quebec Ministry of the Environment and Wildlife','675, Rene-Levesque East Blvd, 7th floor','Quebec City','G1R 5V7','(418) 646-8483','denis.laliberte@mddep.gouv.qc.ca','http://www.mddep.gouv.qc.ca/ministere/inter_en.htm','Province of Quebec','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('RI','NA','Byrns','Michael','Michael Byrns',null,'(401) 222-7766','RI Dept. of Health, Office of Environmental Health Risk Assessment','3 Capitol Hill, Rm 201','Providence, RI','02908-5097','(401) 222-6953','michael.byrns@health.ri.gov','http://www.health.ri.gov/healthrisks/poisoning/mercury/about/fish/','Department of Health - Mercury Poisoning','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('SC','Both','Altman','Chad','Chad Altman',null,'(803) 898-4035','SC Department of Health & Environmental Control','2600 Bull Street','Columbia, SC','29201','(803) 898-3795','Altmankc@dhec.sc.gov','https://www.scdhec.gov/food-safety/food-monitoring-advisories/fish-consumption-advisories','South Carolina Fish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('SD','NA','Minerich','Shannon','Shannon Minerich',null,'(605) 773-4055','SD DENR','5230 East Capitol Avenue','Pierre, SD','57501','(605) 773-6035','Shannon.Minerich@state.sd.us','https://danr.sd.gov/OfficeOfWater/SurfaceWaterQuality/waterqualitystandards/fishflesh.aspx','South Dakota Fish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('SK','NA','Wallace','Rob','Rob Wallace',null,'(306) 933-7100','Saskatchewan Ministry of Environment','112 Research Drive','Saskatoon','S7K 2H6','(306) 933-5773','Rob.Wallace@gov.sk.ca','http://www.environment.gov.sk.ca/','Province of Saskatchewan - Angler Information','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('T2','NA','Frazer','Gary','Gary Frazer',null,'(218) 335-8581','Minnesota Chippewa Tribe Research Lab','P.O. Box 217','Cass Lake, MN','56633','(218) 335-8496','gfrazer@mnchippewatribe.org','http://www.mnchippewatribe.org','Minnesota Chippewa Tribe Homepage','Y','Tribe','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('T3','NA','Corey','Fred','Fred Corey',null,'(207) 764-7765','Aroostook Band of Micmacs Environmental Health Department','8 Northern Rd.','Presque Isle, ME','04769','(207) 764-7768','fcorey@micmac-nsn.gov','http://www.micmac-nsn.gov/html/environmental.html',null,'Y','Tribe','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('T4','NA','David','Tony','Tony David',null,'(518) 358-5937','St. Regis Mohawk Tribe, Environment Division','412 State Route 37','Akwesasne, NY','13655','(518) 358-6252','tony.david@srmt-nsn.gov','https://www.srmt-nsn.gov/news/2019/new-york-state-fish-consumption-advisory-affirms-tribal-guidelines','St. Regis Mohawk Tribe, Environment Division','Y','Tribe','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('T5','NA','Ducheneaux','Carlyle','Carlyle Ducheneaux',null,'(605) 964-6558','Cheyenne River Sioux Tribe Game, Fish & Parks','P.O. Box 590, East Hwy 212','Eagle Butte, SD','57625','(605) 694-1072','Cducheneaux@crstepd.org','http://www.crstgfp.com/',null,'Y','Tribe','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('TN','Both','Arnwine','Debbie','Debbie Arnwine',null,'(615) 532-0703','TN DEC, Division of Water Pollution Control','William R. Snodgrass, TN Tower, 11th Floor, 312 Rosa L. Parks Ave','Nashville, TN','37243','(615) 532-0046','Debbie.Arnwine@tn.gov','https://www.tn.gov/environment/program-areas/wr-water-resources/watershed-stewardship/bacteriological-and-fishing-advisories.html','Tennessee Department of Environment and Conservation - Bacteriological and Fish Tissue Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('TX','Risk Assessment','Wiles','Kirk','Kirk Wiles',null,'(512) 834-6757','Department of State Health Services','8407 Wall Street','Austin, TX','78754','(512) 834-6267','Kirk.Wiles@dshs.texas.gov','https://www.dshs.state.tx.us/seafood/risks-of-eating-fish.aspx#guides','Texas Department of Health - Fish Advisories and Bans','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('US','NA','Larimer','Lisa','Lisa Larimer',null,'(202) 566-1017','USEPA, Office of Water, Standards and Health Protection Division','1301 Constitution Ave, NW Room-5231X, MC-4305T ','Washington, DC','20460','(202) 566-0409','larimer.lisa@epa.gov','https://www.epa.gov/choose-fish-and-shellfish-wisely','EPA Office of Water - National Listing of Fish and Wildlife Advisories','Y','Federal','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('UT','FDA Limits','Harris','Jim','Jim Harris',null,'(801) 536-4360','Utah Division of Water Quality','195 North 1950 West; PO Box 144870','Salt Lake City, UT','84114-4870','(801) 536-4301','jamesharris@utah.gov','https://deq.utah.gov/fish-advisories/utah-fish-advisories','Utah Division of Water Quality','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('VA','Both; Case-by-case','Flammia','Dwight','Dwight Flammia',null,'(804) 864-8127','VA Department of Health, Division of Environmental Epidemiology','109 Governor Street','Richmond, VA','23219','(804) 864-8131','dwight.flammia@vdh.virginia.gov','http://www.vdh.virginia.gov/environmental-health/public-health-toxicology/fish-consumption-advisory/','Virginia Department of Health - Fish Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('VT','Both','Wadman','Pamela','Pamela Wadman',null,'(802) 863-7220','Vermont Department of Health','108 Cherry St.','Burlington, VT','05402','(802) 863-7632','pamela.wadman@vermont.gov','http://healthvermont.gov/health-environment/recreational-water/mercury-fish','Vermont Fish and Wildlife Department - Fishing','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('WA','Risk Assessment/health assessment','Christie','Emerson','Emerson Christie',null,'(360) 236-3176','WA Department of Health','Town Center 3, 243 Israel Road SE','Tumwater, WA','98501','(360) 236-2251','Emerson.Christie@doh.wa.gov','http://www.doh.wa.gov/CommunityandEnvironment/Food/Fish/Advisories','Washington State Department of Health - Fish and Shellfish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('WI','Risk Assessment; Great Lakes Protocol','Hasz','Justine','Amy Dickey',null,'(715) 896-9558','WI Dept. of Natural Resources','101 S. Webster St., P.O. Box 7921','Madison, WI','53707-7921','(608) 266-2244','Justine.Hasz@wi.gov','http://dnr.wi.gov/topic/fishing/consumption/','Fishing Wisconsin - Eating your catch - making healthy choices','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('WV','Both','Murphy','Patrick','Patrick Murphy',null,'(304) 356-4298','Department of Health and Human Resources - Bureau for Public Health','350 Capitol Street, Room 313','Charleston, WV','25301-3713','(304) 558-0324','Patrick.M.Murphy@wv.gov','https://oehs.wvdhhr.org/fish','West Virginia Fish Consumption Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('WY','NA','Neebling','Travis','Travis Neebling',null,'(307) 233-6410','Wyoming Game and Fish Department','3030 Energy Lane','Casper, WY','82604','(307) 473-3433','Travis.Neebling@wyo.gov','https://wgfd.wyo.gov/Fishing-and-Boating/Fish-Consumption-Advice/','Wyoming Game and Fish Department','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('YT','NA','Toews','Don','Communications Branch','Fisheries Management - Pacific Region','(604) 666-7120','Yukon Renewable Resources','10 Burns Road','Whitehorse','Y1A 4Y9',null,'info@dfo-mpo.gc.ca','http://www.pac.dfo-mpo.gc.ca/ops/fm/fishmgmt_e.htm','Yukon Territory Homepage','Y','Canadian','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('AS','NA','unavailable','Currently','Currently unavailable',null,'(684) 633-2304','American Samoa EPA','PO Box PPA ','Pago Pago, AS','96799','(684) 633-5801','Currently unavailable','http://www.wpcouncil.org/fisheries/american-samoa-archipelago/','American Samoa Government','Y','Territory','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('DC','NA','Shulterbrandt','Nicoline','Nicoline Shulterbrandt',null,'(202) 535-2600','Department of Energy and Environment','1200 First St., NE  5th Floor','Washington, DC','20002','(202) 535-1363','nicoline.shulterbrandt@dc.gov','http://doee.dc.gov/service/fishing-district','Distric Department of the Environment:  Fisheries and Wildlife Public Health Advisory','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('GA','Risk Assessment','Booth','Elizabeth','Elizabeth Booth',null,'(470) 607-2439','Department of Natural Resources, Watershed Protection Branch','4220 International Pkwy, Suite 101','Atlanta, GA','30354','(404) 675-6244','Elizabeth.Booth@dnr.ga.gov','http://epd.georgia.gov/fish-consumption-guidelines','Georgia Department of Natural Resources - Fish Consumption Guidelines','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('VI','NA','Habtes','Sennai','Sennai Habtes',null,'(340) 775-6762 ext 5201','Deparment of Natural Resources, Fish and Wildlife Service','6291 Estate Nazareth, St. Thomas, USVI 00820','St. Thomas, VI','00802',null,'Sennai.habtes@dpnr.vi.gov','https://dpnr.vi.gov/fish-and-wildlife/','U.S. Virgin Islands Department of Planning and Natural Resources','Y','Territory','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('T1','NA','Ackley','Caren','Caren Ackley',null,'(715) 360-4262','Great Lakes Indian Fish and Wildlife Commission (GLIFWC)','72682 Maple Street P.O. Box 9','Odanah, WI','54861',null,'cackley@glifwc.org','http://www.glifwc.org/','Great Lakes Indian Fish and Wildlife Commission','Y','Tribe','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('AK','Risk Assessment','Coburn','Sarah','Sarah Coburn',null,'(651) 201-4243','Alaska Dept of Environmental Conservation','5251 Dr. Martin Luther King Jr. Ave.','Anchorage, AK','99507','(907) 929-7335','sarah.coburn@alaska.gov','http://dec.alaska.gov/eh/vet/fish-monitoring-program','Alaska Fish Facts & Consumption guidelines','Y','State','N');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NM','NA','Fristachi','Tony','Tony Fristachi',null,'(505) 827-2767','New Mexico Department of Health, Environmental Public Health Tracking Program','1190 St. Francis Dr., Suite N1259','Santa Fe, NM','87502',null,'anthony.fristachi@state.nm.us','https://nmtracking.doh.nm.gov/environment/contaminants/FishConsumption.html',null,'Y','State','N');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('NY','FDA Limits; DoH method','Parker','Colleen','Colleen Parker',null,'(518) 402-7800','NY State Department of Health','NYSDOH, Corning Tower, Empire State Plaza','Albany, NY','12237','(518) 402-7819','Colleen.Parker@health.ny.gov','https://www.health.ny.gov/environmental/outdoors/fish/health_advisories/','New York DOH - Health Advisories','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('IL','FDA Limits','Koch','Brian','Brian Koch',null,'(217) 785-3176','IL Department of Health','Division of Environmental Health 525 W. Jefferson St.','Springfield, IL','62761',null,'Brian.koch@illinois.gov','http://dph.illinois.gov/topics-services/environmental-health-protection/toxicology/fish-advisories',null,'Y','State','N');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('PA','FDA Limits; Great Lakes Protocol','Wertz','Tim','Tim Wertz',null,'(717) 787-9637','PA DEP. Division of Water Quality Standards','400 Market Street, 11th Floor PO Box  8774','Harrisburg, PA','17105-8774','(717) 772-3249','twertz@pa.gov','http://www.dep.pa.gov/Business/Water/CleanWater/WaterQuality/FishConsumptionAdvisory/Pages/default.aspx','Pennsylvania Department of Environmental Protection Public Health Advisory','Y','State','Y');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('MS','Both','O''Pry','Brannon','Brannon O''Pry',null,'(601) 961-5688','MDEQ, Field Services','P.O. Box 2261','Jackson, MS','39225','(601) 961-5704','bopry@mdeq.ms.gov','https://www.mdeq.ms.gov/water/field-services/fish-advisories-fish-tissue-and-fishing-bans/','MDEQ - Mississippi Fish Advisories Field Services Division','Y','State','N');
Insert into NLFWA.METHOD (STATE,METHOD,LNAME,FNAME,NAME,TITLE,PHONE_NUMB,AGENCY,ADDRESS,CITY,ZIP,FAX,EMAIL,STATEURL,STATEURLTEXT,CURRINFO,AFFILIATION,IS_DEFAULT) values ('PA','FDA Limits; Great Lakes Protocol','Wertz','Tim','Tim Wertz',null,'(717) 787-9637','PA DEP. Division of Water Quality Standards','400 Market Street, 11th Floor PO Box  8774','Harrisburg, PA','17105-8774','(717) 772-3249','twertz@pa.gov','https://files.dep.state.pa.us/water/drinking%20water%20and%20facility%20regulation/WaterQualityPortalFiles/FishConsumption/FishAdvisory/FINAL-2020-Pa%20Fishing%20Summary-web_12-5-19-FCAs.pdf','Pennsylvania Department of Environmental Protection Public Health Advisory','Y','State','N');
--------------------------------------------------------
--  DDL for Index METHOD_IDX_STATE
--------------------------------------------------------

  CREATE INDEX "NLFWA"."METHOD_IDX_STATE" ON "NLFWA"."METHOD" ("STATE") 
  ;
--------------------------------------------------------
--  DDL for Index METHOD_IDX_IS_DEFAULT
--------------------------------------------------------

  CREATE BITMAP INDEX "NLFWA"."METHOD_IDX_IS_DEFAULT" ON "NLFWA"."METHOD" ("IS_DEFAULT") 
  ;
--------------------------------------------------------
--  DDL for Index METHOD_STATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NLFWA"."METHOD_STATE_PK" ON "NLFWA"."METHOD" ("STATE", "NAME", "STATEURL") 
  ;
--------------------------------------------------------
--  Constraints for Table METHOD
--------------------------------------------------------

  ALTER TABLE "NLFWA"."METHOD" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "NLFWA"."METHOD" MODIFY ("METHOD" NOT NULL ENABLE);
  ALTER TABLE "NLFWA"."METHOD" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "NLFWA"."METHOD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "NLFWA"."METHOD" MODIFY ("AGENCY" NOT NULL ENABLE);
  ALTER TABLE "NLFWA"."METHOD" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "NLFWA"."METHOD" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "NLFWA"."METHOD" MODIFY ("ZIP" NOT NULL ENABLE);
  ALTER TABLE "NLFWA"."METHOD" MODIFY ("CURRINFO" NOT NULL ENABLE);
  ALTER TABLE "NLFWA"."METHOD" MODIFY ("AFFILIATION" NOT NULL ENABLE);
  ALTER TABLE "NLFWA"."METHOD" ADD CONSTRAINT "METHOD_AFFILIATION_CK" CHECK ( affiliation IN('Canadian','Federal','State','Territory','Tribe')) ENABLE;
  ALTER TABLE "NLFWA"."METHOD" ADD CONSTRAINT "METHOD_CURRINFO_CK" CHECK ( currinfo IN('Y','N')) ENABLE;
  ALTER TABLE "NLFWA"."METHOD" MODIFY ("STATEURL" NOT NULL ENABLE);
  ALTER TABLE "NLFWA"."METHOD" ADD CONSTRAINT "METHOD_STATE_PK" PRIMARY KEY ("STATE", "NAME", "STATEURL")
  USING INDEX  ENABLE;
  ALTER TABLE "NLFWA"."METHOD" MODIFY ("IS_DEFAULT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table METHOD
--------------------------------------------------------

  ALTER TABLE "NLFWA"."METHOD" ADD CONSTRAINT "METHOD_STATE_FK" FOREIGN KEY ("STATE")
	  REFERENCES "NLFWA"."STATES" ("STATE") ENABLE;
